# This is a basic workflow to compile an AutoHotKey script based on # https://github.com/marketplace/actions/ahk2exe
# NOTE: Tagging is important if you want a Release generated (e.g. git tag -a v0.24.04 -m "Valheim KeyBuddy v0.24")
#       You must push the tags separately (e.g. git push origin v0.24.04) and only then will the release be generated.
name: nukdokplex - Compile Valheim-KeyBuddy.ahk and generate a release if a tag is pushed (Triggered on push to main or spike/*)

# Controls when the action will run. Workflow runs when code is pushed to main or spike/*
on:
  push:
    branches: 
              - main
              - 'spike/**'
    tags:
              - "v*.*.*"


jobs:
  build:
    name: Compile Valheim Version
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with AHK v1.1.33.01
        uses: nukdokplex/autohotkey-build@v0.1
        with:
          version: v1.1.33.01
          x64: true
          x86: false
          compression: none
          in: Valheim-KeyBuddy.ahk
      - name: Check for compiled binary and .ahk
        shell: pwsh
        run: |
            ls 
            ls KeyBuddy-Valheim
            ls ..\

