# This is a basic workflow to compile an AutoHotKey script based on # https://github.com/marketplace/actions/ahk2exe

name: Compile hello-world.ahk AutoHotKey Spike (Triggered on push to main or spike/*)

# Controls when the action will run. Workflow runs when code is pushed to main or spike/*
on:
  push:
    branches: 
              - main
              - 'spike/**'
    tags:
              - "v*.*.*"
  pull_request:
    branches: 
              - 'compile/**'
              - 'spike/**'
              - 'release/**'

jobs:
  Example:
    name: Compile with Ahk2Exe
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: Valheim-KeyBuddy.ahk

      - name: Check for compiled binary
        shell: pwsh
        run: |
          ls KeyBuddy-Valheim

# https://github.com/marketplace/actions/gh-release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        with:
          body: 
            Turns out ${{ github.workspace }}vhkb-releasenotes.txt was not the appropriate path for release notes.
          body_path: 
            ${{ github.workspace }}vhkb-releasenotes.txt
          files: 
            KeyBuddy-Valheim/KeyBuddy - Valheim.exe
