# This is a basic workflow to compile an AutoHotKey script based on # https://github.com/marketplace/actions/ahk2exe
# NOTE: Tagging is important if you want a Release generated (e.g. git tag -a v0.24.04 -m "Valheim KeyBuddy v0.24")
#       You must push the tags separately (e.g. git push origin v0.24.04) and only then will the release be generated.
name: Compile Valheim-KeyBuddy.ahk and generate a release if a tag is pushed (Triggered on push to main or spike/*)

# Controls when the action will run. Workflow runs when code is pushed to main or spike/*
on:
  push:
    branches: 
              - main
              - 'spike/**'
    tags:
              - "v*.*.*"
  pull_request:
    branches: 
              - 'compile/**'
              - 'spike/**'
              - 'release/**'

jobs:
  Example:
    name: Compile with Ahk2Exe
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: Valheim-KeyBuddy.ahk

      - name: Check for compiled binary
        shell: pwsh
        run: |
          ls KeyBuddy-Valheim

# https://github.com/marketplace/actions/gh-release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        with:
          body: 
            Turns out vhkb-releasenotes.txt was not the appropriate path for release notes.
          body_path: 
            vhkb-releasenotes.txt
          files: 
            KeyBuddy-Valheim/KeyBuddy - Valheim.exe
